[package]
name = "hflow"
version = "0.1.0"
edition = "2024"
authors = ["cvalend [cvalendb@outlook.com]"]
description = "A lightweight concurrent task progress manager for CLI applications."



[dependencies]
colored = "3.1.1"